#############################################################
## ADJUSTABLE PARAMETERS                                   ##
#############################################################

structure          ligand.psf
coordinates        ligand.pdb
outputName         lig

seed               12345
#############################################################
## SIMULATION PARAMETERS                                   ##
#############################################################

# Input
paraTypeCharmm      on
parameters          par_all36_prot.prm
parameters          par_all36_cgenff.prm
parameters          ligand.str
parameters          toppar_water_ions.str

# NOTE: Do not set the initial velocity temperature if you 
# have also specified a .vel restart file!
temperature         310

numsteps 1 
COMmotion yes
# Periodic Boundary Conditions
# NOTE: Do not set the periodic cell basis if you have also 
# specified an .xsc restart file!


### gbsa
GBIS on
solventDielectric 78.5
ionConcentration 0.15
alphaCutoff 15.


SASA on
surfaceTension 0.0072


# Force-Field Parameters
exclude scaled1-4
cutoff 16.
switching  on
switchdist 15.


set ts 0

coorfile open dcd ligand.dcd

while {[coorfile read] != -1 } {
    firstTimestep $ts
    run 0
    incr ts 1
}
coorfile close
