#############################################################
## JOB DESCRIPTION                                         ##
#############################################################

# Minimization and Equilibration of 
# Ubiquitin in a Water Box


#############################################################
## ADJUSTABLE PARAMETERS                                   ##
#############################################################

structure          www.psf
coordinates        www.pdb

firsttimestep      0


#############################################################
## SIMULATION PARAMETERS                                   ##
#############################################################

# Input
paraTypeCharmm	    on
parameters  par_all36_prot.prm
parameters  par_all36_cgenff.prm
parameters  ligand.str
parameters  toppar_water_ions.str
temperature         310.0

seed   12345
# Force-Field Parameters
exclude             scaled1-4
1-4scaling          1.0
cutoff              16.0
switching           on
switchdist          15.
pairlistdist        16.0


# Integrator Parameters
timestep            1.0  ;# 2fs/step
rigidBonds          all  ;# needed for 2fs steps
nonbondedFreq       1
fullElectFrequency  1  
stepspercycle       10


# Constant Temperature Control
langevin            on    ;# do langevin dynamics
langevinDamping     1     ;# damping coefficient (gamma) of 1/ps
langevinTemp        310.0
langevinHydrogen    off    ;# don't couple langevin bath to hydrogens


# Periodic Boundary Conditions
cellBasisVector1    42.0    0.   0.0
cellBasisVector2     0.0  44.0   0.0
cellBasisVector3     0.0    0   47.0
cellOrigin          31.0   29.0  17.5

wrapAll             on


# PME (for full-system periodic electrostatics)
PME                 yes
PMEGridSpacing      1.0

#manual grid definition
#PMEGridSizeX        45
#PMEGridSizeY        45
#PMEGridSizeZ        48


# Constant Pressure Control (variable volume)
useGroupPressure      yes ;# needed for rigidBonds
useFlexibleCell       no
useConstantArea       no

langevinPiston        on
langevinPistonTarget  1.01325 ;#  in bar -> 1 atm
langevinPistonPeriod  100.0
langevinPistonDecay   50.0
langevinPistonTemp    310.0


# Output
outputName          com_md

restartfreq         1     ;# 500steps = every 1ps
dcdfreq             1
xstFreq             1
outputEnergies      1
outputPressure      1


#############################################################
## EXTRA PARAMETERS                                        ##
#############################################################


#############################################################
## EXECUTION SCRIPT                                        ##
#############################################################

# Minimization
minimize            20
run 40 ;


